---
title: "Decision_tree"
author: "Yiling Yang"
date: "11/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE,message = FALSE)
library(tidyverse)
library(readxl)
library(rpart)
library(rpart.plot)

load('seizure20A.Rdat')
load('seizure20B.Rdat')
load('seizure20C.Rdat')
```


```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure20A)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure20A,method='class')
sum(seizure20A$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```



```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure20B)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure20B,method='class')
sum(seizure20B$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```


```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure20C)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure20C,method='class')
sum(seizure20C$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```


```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure60A)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure60A,method='class')
sum(seizure60A$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```

```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure60B)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure60B,method='class')
sum(seizure60B$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```


```{r}
fit <- rpart(success ~ age1 + Male + pre + se_duration + final_dx  + home_med,
   method="class", data=seizure60C)

print(fit)
rpart.plot(fit)


pred <- predict(fit,newdata = seizure60C,method='class')
sum(seizure60C$success == as.character(as.numeric(pred[,1]<pred[,2])))/length(pred)
```




